// ── 100 scenarios de test MecaIA — battery_scenarios.mjs ─────────────────
// 100 vehicules differents · 100 systemes differents · 100 pannes differentes
// Carburants: essence, diesel, hybride, GPL, electrique
// Systemes: moteur, injection, emission, transmission, freinage,
//           refroidissement, electrique, suspension, direction, climatisation

export const BATTERY = [
// ── GROUPE 1 : Codes moteur P0 — melange/injection (20) ──────────────────
{ id:1,  make:'Renault', model:'Clio IV', year:2016, fuel:'diesel', km:87000, sys:'EGR',
  msg:'Code P0401 EGR debit insuffisant. Renault Clio IV 1.5 dCi 2016 87000km. Voyant fixe, surconsommation +1L/100.', expect:['EGR','nettoyage','spray'] },
{ id:2,  make:'Peugeot', model:'208', year:2018, fuel:'essence', km:52000, sys:'Catalyseur',
  msg:'P0420 efficacite catalyseur insuffisante. Peugeot 208 1.2 PureTech 2018 52000km. Voyant allume depuis 1 semaine.', expect:['catalyseur','sonde lambda','bouchon reservoir'] },
{ id:3,  make:'Volkswagen', model:'Golf VII', year:2015, fuel:'diesel', km:143000, sys:'FAP',
  msg:'P2002 filtre a particules - efficacite insuffisante. VW Golf 7 2.0 TDI 2015 143000km. Regeneration FAP impossible.', expect:['FAP','regeneration','additif'] },
{ id:4,  make:'BMW', model:'Série 1 F20', year:2014, fuel:'essence', km:98000, sys:'Allumage',
  msg:'P0301 rates allumage cylindre 1. BMW 116i F20 1.6 2014 98000km. Vibrations au ralenti, cale parfois.', expect:['bobine','bougie','permutation'] },
{ id:5,  make:'Toyota', model:'Yaris III', year:2017, fuel:'hybride', km:67000, sys:'Systeme hybride',
  msg:'Voyant hybride + P3000. Toyota Yaris hybride 2017 67000km. Message erreur batterie haute tension.', expect:['batterie HV','garage Toyota','urgence'] },
{ id:6,  make:'Ford', model:'Focus III', year:2013, fuel:'essence', km:112000, sys:'EVAP',
  msg:'P0456 petite fuite systeme evaporation carburant. Ford Focus 1.6 EcoBoost 2013 112000km.', expect:['bouchon reservoir','fuite','EVAP'] },
{ id:7,  make:'Opel', model:'Astra K', year:2016, fuel:'diesel', km:78000, sys:'Injecteurs',
  msg:'P0201 circuit injecteur cylindre 1 ouvert. Opel Astra 1.6 CDTI 2016 78000km. A-coup en acceleration.', expect:['injecteur','circuit electrique','resistance'] },
{ id:8,  make:'Citroën', model:'C3 III', year:2018, fuel:'essence', km:41000, sys:'Richesse',
  msg:'P0171 melange trop pauvre banc 1. Citroen C3 1.2 PureTech 2018 41000km. LTFT +12%. Consommation ok.', expect:['LTFT','fuite admission','debitmetre'] },
{ id:9,  make:'Fiat', model:'500X', year:2016, fuel:'diesel', km:89000, sys:'Turbo',
  msg:'P0299 pression suralimentation insuffisante. Fiat 500X 1.6 MultiJet 2016 89000km. Perte puissance notable.', expect:['turbo VNT','boost','durite'] },
{ id:10, make:'Skoda', model:'Octavia III', year:2015, fuel:'essence', km:134000, sys:'Soupapes',
  msg:'P0011 calage arbre cames admission avance. Skoda Octavia 1.4 TSI 2015 134000km. Cliquetis a froid.', expect:['VANOS','solenoide','huile'] },
{ id:11, make:'Mercedes', model:'Classe A W176', year:2014, fuel:'diesel', km:156000, sys:'SCR AdBlue',
  msg:'P20E8 reducteur reagent insuffisant. Mercedes A200 CDI 2014 156000km. Alarme AdBlue, 1000km avant blocage.', expect:['AdBlue','remplir','qualite'] },
{ id:12, make:'Audi', model:'A3 8V', year:2016, fuel:'essence', km:73000, sys:'Injection directe',
  msg:'P0087 pression carburant insuffisante. Audi A3 1.4 TFSI 2016 73000km. Rates sous charge, demar difficile.', expect:['pompe carburant','pression','rail'] },
{ id:13, make:'Hyundai', model:'i20', year:2018, fuel:'essence', km:45000, sys:'MAF',
  msg:'P0101 circuit debitmetre hors plage. Hyundai i20 1.2 MPI 2018 45000km. Consommation augmentee.', expect:['MAF','nettoyage spray','remplacement'] },
{ id:14, make:'Kia', model:'Ceed III', year:2019, fuel:'diesel', km:61000, sys:'EGR',
  msg:'P0404 circuit vanne EGR hors plage. Kia Ceed 1.6 CRDi 2019 61000km. Fumee noire legere en acceleration.', expect:['EGR','nettoyage','fumee'] },
{ id:15, make:'Seat', model:'Ibiza V', year:2017, fuel:'essence', km:58000, sys:'Lambda',
  msg:'P0137 tension sonde O2 aval trop basse. Seat Ibiza 1.0 TSI 2017 58000km.', expect:['sonde lambda aval','catalyseur','circuit'] },
{ id:16, make:'Nissan', model:'Qashqai II', year:2016, fuel:'diesel', km:92000, sys:'FAP + EGR',
  msg:'P2463 suie accumulees FAP + P0401. Nissan Qashqai 1.5 dCi 2016 92000km. FAP bouche, impossibilite regenerer.', expect:['FAP','EGR','regeneration forcee'] },
{ id:17, make:'Dacia', model:'Duster II', year:2018, fuel:'essence', km:38000, sys:'Allumage',
  msg:'P0304 rates cylindre 4. Dacia Duster 1.3 TCe 2018 38000km. Tremblement fort au ralenti.', expect:['bobine C4','permutation','bougie'] },
{ id:18, make:'Volvo', model:'V40', year:2015, fuel:'diesel', km:118000, sys:'Admission',
  msg:'P0234 surcompression detectee. Volvo V40 D2 2015 118000km. Coupure puissance par protection moteur.', expect:['turbo','soupape wastegate','durite'] },
{ id:19, make:'Mini', model:'Cooper F56', year:2016, fuel:'essence', km:64000, sys:'EVAP',
  msg:'P0441 purge EVAP incorrecte. Mini Cooper 1.5 2016 64000km. Odeur carburant leger.', expect:['canister','electrovanne purge','bouchon'] },
{ id:20, make:'Suzuki', model:'Vitara', year:2017, fuel:'essence', km:49000, sys:'Ralenti',
  msg:'P0507 regime ralenti trop eleve. Suzuki Vitara 1.4 BoosterJet 2017 49000km. Ralenti 1200tpm au lieu de 750.', expect:['papillon','corps etrangleur','capteur'] },

// ── GROUPE 2 : Codes transmission P07 (10) ─────────────────────────────────
{ id:21, make:'Renault', model:'Megane IV', year:2017, fuel:'diesel', km:73000, sys:'Boite EDC',
  msg:'P0730 rapport boite de vitesses incorrect. Renault Megane IV 1.5 dCi EDC 2017 73000km. A-coups au passage des vitesses.', expect:['EDC','huile boite','adaptations'] },
{ id:22, make:'Volkswagen', model:'Passat B8', year:2016, fuel:'diesel', km:112000, sys:'DSG',
  msg:'P0732 rapport 2 incorrect. VW Passat 2.0 TDI DSG7 2016 112000km. Choc au passage en 2e.', expect:['DSG','mécatronique','huile DSG'] },
{ id:23, make:'BMW', model:'Série 5 F10', year:2013, fuel:'diesel', km:189000, sys:'BVA',
  msg:'P0868 pression huile boite faible. BMW 520d F10 2013 189000km. BVA patine, vibration en Drive.', expect:['BVA','niveau huile','ZF'] },
{ id:24, make:'Peugeot', model:'308 II', year:2015, fuel:'essence', km:97000, sys:'EAT6',
  msg:'P0961 solenoides regulation pression boite. Peugeot 308 1.6 THP EAT6 2015 97000km. Boite se bloque en 3e.', expect:['boite auto','solenoides','vidange'] },
{ id:25, make:'Ford', model:'S-Max', year:2015, fuel:'diesel', km:145000, sys:'PowerShift',
  msg:'P0751 solenoid A bloque. Ford S-Max 2.0 TDCi PowerShift 2015 145000km. Patinage boite, chauffe anormale.', expect:['PowerShift','mecatronique','Ford specific'] },
{ id:26, make:'Toyota', model:'Auris Hybrid', year:2014, fuel:'hybride', km:78000, sys:'CVT hybride',
  msg:'P3190 puissance moteur insuffisante systeme hybride. Toyota Auris hybride 2014 78000km. Mode EV perdu.', expect:['hybride','batterie','garage Toyota'] },
{ id:27, make:'Citroen', model:'DS5', year:2013, fuel:'diesel', km:134000, sys:'EAT8',
  msg:'P0722 signal capteur vitesse sortie boite absent. Citroen DS5 2.0 BlueHDi 2013 134000km. Boite reste en defaut.', expect:['capteur vitesse','boite','circuit'] },
{ id:28, make:'Opel', model:'Insignia B', year:2017, fuel:'essence', km:67000, sys:'Hydra-Matic',
  msg:'P0706 circuit capteur position selecteur incorrect. Opel Insignia 1.5 Turbo 2017 67000km.', expect:['selecteur','position BVA','capteur'] },
{ id:29, make:'Audi', model:'Q5 FY', year:2018, fuel:'diesel', km:89000, sys:'Quattro S-tronic',
  msg:'P0811 patinage embrayage excessif. Audi Q5 3.0 TDI 2018 89000km. Vibration au demarrage.', expect:['embrayage','S-tronic','DSG'] },
{ id:30, make:'Mercedes', model:'Vito W447', year:2016, fuel:'diesel', km:156000, sys:'722.9',
  msg:'P0730 + P0868. Mercedes Vito 2.2 CDI 7G-Tronic 2016 156000km. Passages brutaux.', expect:['7G-Tronic','huile boite','conducteur'] },

// ── GROUPE 3 : Symptomes sans code — bruits, vibrations, comportement (20] ─
{ id:31, make:'BMW', model:'E46 320d', year:2003, fuel:'diesel', km:176000, sys:'Distribution',
  msg:'BMW E46 320d 2003 176000km. Cliquetis metallique au demarrage froid 3-4 secondes puis disparait. Aucun code.', expect:['chaine','tendeur','huile'] },
{ id:32, make:'Volkswagen', model:'Polo VI', year:2019, fuel:'essence', km:34000, sys:'Freinage',
  msg:'VW Polo 1.0 TSI 2019 34000km. Grincement freins avant uniquement au premier freinage le matin. Disparait ensuite.', expect:['rouille','patins','normal le matin'] },
{ id:33, make:'Renault', model:'Kangoo III', year:2020, fuel:'diesel', km:67000, sys:'Direction',
  msg:'Renault Kangoo 1.5 dCi 2020 67000km. Coup de barre a droite sur chaussee dégradée, craquement colonne.', expect:['rotule','cardan','silent bloc'] },
{ id:34, make:'Peugeot', model:'3008 II', year:2018, fuel:'diesel', km:78000, sys:'Climatisation',
  msg:'Peugeot 3008 1.6 BlueHDi 2018 78000km. Climatisation insufflante de lair chaud au lieu de froid. Compresseur enclenche.', expect:['fluide frigorigene','compresseur','vidange clim'] },
{ id:35, make:'Toyota', model:'RAV4 V', year:2019, fuel:'hybride', km:42000, sys:'Freinage regen',
  msg:'Toyota RAV4 hybride 2019 42000km. Pedale de frein qui vibre quand la voiture ralentit toute seule (regen). Normal ?', expect:['normal hybride','regen','confirmation'] },
{ id:36, make:'Ford', model:'Fiesta VII', year:2017, fuel:'essence', km:89000, sys:'Suspension',
  msg:'Ford Fiesta 1.0 EcoBoost 2017 89000km. Bruit sourd en virage a gauche uniquement. Amplifie a grande vitesse.', expect:['roulement','bruit amplifie virage','cote gauche'] },
{ id:37, make:'Citroen', model:'Berlingo III', year:2019, fuel:'diesel', km:56000, sys:'Embrayage',
  msg:'Citroen Berlingo 1.5 BlueHDi 2019 56000km. Odeur de brule en cote avec chargement lourd. Pedale dure.', expect:['embrayage','usure','chauffement'] },
{ id:38, make:'Mercedes', model:'Sprinter W907', year:2020, fuel:'diesel', km:134000, sys:'Injection',
  msg:'Mercedes Sprinter 2.0 CDI 2020 134000km. Demarrage difficile par temps froid sous -5C. Fume blanc au demarrage.', expect:['prechauffage','bougies','temperature'] },
{ id:39, make:'Nissan', model:'Leaf II', year:2018, fuel:'electrique', km:45000, sys:'Batterie VE',
  msg:'Nissan Leaf 40kWh 2018 45000km. Autonomie tombee a 180km au lieu de 280km. Pas de voyant. Degradation batterie ?', expect:['degradation batterie','cellules','normal utilisation'] },
{ id:40, make:'Honda', model:'CR-V V', year:2019, fuel:'hybride', km:38000, sys:'AWD hybride',
  msg:'Honda CR-V 1.5 VTEC Turbo 4WD 2019 38000km. Vibrations a 110 km/h uniquement. Pas de code.', expect:['balourd pneu','equilibrage','transmission'] },
{ id:41, make:'Skoda', model:'Fabia III', year:2016, fuel:'essence', km:76000, sys:'Direction',
  msg:'Skoda Fabia 1.2 TSI 2016 76000km. Volant dur apres redemarrage moteur froid. Direction assistee electrique.', expect:['DASM','colonne','capteur couple'] },
{ id:42, make:'Seat', model:'Ateca', year:2017, fuel:'diesel', km:91000, sys:'4x4',
  msg:'Seat Ateca 2.0 TDI 4Drive 2017 91000km. Vibration en prenant les virages lents. Accroche du 4x4.', expect:['differentiel','transfert','embrayage Haldex'] },
{ id:43, make:'Dacia', model:'Logan MCV', year:2015, fuel:'GPL', km:167000, sys:'Carburation GPL',
  msg:'Dacia Logan 1.6 MPI GPL 2015 167000km. Demarrage essence OK mais passage en GPL difficile. Rate un peu.', expect:['injecteurs GPL','filtre GPL','regulateur'] },
{ id:44, make:'Hyundai', model:'Tucson III', year:2019, fuel:'essence', km:52000, sys:'Freinage',
  msg:'Hyundai Tucson 1.6 T-GDi 2019 52000km. Pedal de frein trop mou. Faut appuyer plus fort qu avant.', expect:['liquide frein','plaquettes','maitre cylindre'] },
{ id:45, make:'Kia', model:'Sportage IV', year:2017, fuel:'diesel', km:87000, sys:'Echappement',
  msg:'Kia Sportage 1.7 CRDi 2017 87000km. Bruit de sifflement sous le plancher en deceleration. Odeur fugace echappement.', expect:['fuite echappement','joint','sifflement'] },
{ id:46, make:'Volvo', model:'XC40', year:2019, fuel:'essence', km:43000, sys:'Turbo',
  msg:'Volvo XC40 2.0 T4 2019 43000km. Sifflement turbo perceptible seulement en forte acceleration. Puissance normale.', expect:['turbo debut usure','durite','verification'] },
{ id:47, make:'Mini', model:'Countryman F60', year:2017, fuel:'essence', km:67000, sys:'VANOS',
  msg:'Mini Countryman 2.0 SD 2017 67000km. Grognement a froid au ralenti qui disparait apres 3 min. Huile B47 propre.', expect:['VANOS','chaine','tenseur'] },
{ id:48, make:'Alfa Romeo', model:'Giulia', year:2017, fuel:'diesel', km:98000, sys:'Transmission',
  msg:'Alfa Romeo Giulia 2.2 JTDm 2017 98000km. Vibration pedale au freinage entre 120 et 80 km/h. Disques neufs il y a 20000km.', expect:['voile disque','gauchissement','chaleur'] },
{ id:49, make:'Fiat', model:'Ducato IV', year:2018, fuel:'diesel', km:189000, sys:'Freinage poids lourd',
  msg:'Fiat Ducato 2.3 MultiJet 2018 189000km. Pedale de frein qui descend lentement sous pied constant. Fuite circuit?', expect:['maitre cylindre','fuite lente','circuit'] },
{ id:50, make:'Land Rover', model:'Discovery Sport', year:2018, fuel:'diesel', km:73000, sys:'AWD',
  msg:'Land Rover Discovery Sport 2.0 D180 2018 73000km. Accrochage transmission en manoeuvre parking. Mode 4x4 constant.', expect:['differentiel','embrayage visqueux','desactivation'] },

// ── GROUPE 4 : Systemes electriques — batterie, alternateur, electronique (15) ─
{ id:51, make:'Renault', model:'Zoe ZE50', year:2020, fuel:'electrique', km:38000, sys:'Chargeur embarque',
  msg:'Renault Zoe R135 ZE50 2020 38000km. Charge AC lente, bridee a 5kW au lieu de 22kW. Message erreur chargeur.', expect:['chargeur embarque','mode dégradé','Renault charge'] },
{ id:52, make:'Peugeot', model:'e-208', year:2020, fuel:'electrique', km:29000, sys:'Pompe chaleur',
  msg:'Peugeot e-208 2020 29000km. Chauffage insuffisant en hiver. Pompe a chaleur non active selon ecran.', expect:['pompe chaleur','refrigerant','capteur'] },
{ id:53, make:'BMW', model:'330e G20', year:2020, fuel:'hybride rechargeable', km:42000, sys:'PHEV',
  msg:'BMW 330e 2020 42000km. Mode electrique uniquement 20km au lieu de 60km annonces. Charge complete OK.', expect:['degradation batterie','mode hybride','facteurs externes'] },
{ id:54, make:'Volkswagen', model:'ID.3 Pro', year:2021, fuel:'electrique', km:31000, sys:'Pompe AC',
  msg:'VW ID.3 Pro 2021 31000km. Climatisation tombe en panne quand temperature exterieure depasse 35°C. Surchauffe onduleur.', expect:['onduleur','refroidissement electronique','alerte'] },
{ id:55, make:'Toyota', model:'Camry Hybrid', year:2018, fuel:'hybride', km:87000, sys:'ICE+electrique',
  msg:'Toyota Camry hybride 2018 87000km. Mode EV ne s active plus. Batterie 12V OK. Pas de code diagnostic.', expect:['batterie hybride NiMH','seuil charge','Toyota diagnostic'] },
{ id:56, make:'Audi', model:'A6 C8', year:2019, fuel:'diesel mild hybrid', km:54000, sys:'BSG 48V',
  msg:'Audi A6 3.0 TDI MHEV 2019 54000km. Warning systeme 48V, arret auto moteur plus disponible. Batterie 48V?', expect:['batterie 48V lithium','BSG','remplacement'] },
{ id:57, make:'Mercedes', model:'CLA W118', year:2020, fuel:'essence', km:47000, sys:'Start/stop',
  msg:'Mercedes CLA 200 2020 47000km. Start/stop ne fonctionne plus depuis 2 semaines. Batterie AGM neuve il y a 3 mois.', expect:['BMS','apprentissage batterie','capteur EFB'] },
{ id:58, make:'Ford', model:'Kuga III PHEV', year:2021, fuel:'hybride rechargeable', km:38000, sys:'Rappel connu',
  msg:'Ford Kuga PHEV 2021 38000km. Probleme charge incomplète, arrete a 70%. Rappel constructeur en cours?', expect:['rappel Ford','mise a jour logicielle','contact Ford'] },
{ id:59, make:'Renault', model:'Megane III', year:2012, fuel:'diesel', km:156000, sys:'Alternateur',
  msg:'Renault Megane III 1.5 dCi 2012 156000km. Voyant batterie allume, tension 12.1V moteur tourne. Radio eteint.', expect:['alternateur','tension insuffisante','remplacement'] },
{ id:60, make:'Opel', model:'Mokka A', year:2014, fuel:'essence', km:112000, sys:'Centralisation',
  msg:'Opel Mokka 1.4 Turbo 2014 112000km. Portes ne se verrouillent plus via telecommande. Pile changee, meme probleme.', expect:['UC carrosserie','signal radio','synchro telecommande'] },
{ id:61, make:'Hyundai', model:'IONIQ Electric', year:2019, fuel:'electrique', km:52000, sys:'Recharge rapide',
  msg:'Hyundai IONIQ Electric 28kWh 2019 52000km. Recharge DC rapide bloquee a 30kW au lieu de 50kW. AC 7.2kW normal.', expect:['batterie chaude','limitation thermique','protection batterie'] },
{ id:62, make:'Citroën', model:'C4 Picasso II', year:2014, fuel:'diesel', km:143000, sys:'Bougies',
  msg:'Citroen Grand C4 Picasso 2.0 BlueHDi 2014 143000km. Demarrage difficile a froid sous 5°C. Bougies d allumage vieilles?', expect:['bougies prechauffage','temperature','delai'] },
{ id:63, make:'Fiat', model:'Panda III', year:2016, fuel:'GPL', km:89000, sys:'Batterie 12V',
  msg:'Fiat Panda 1.2 GPL 2016 89000km. Cle dans contact, rien ne se passe. Ni demarrage, ni electricite. Batterie?', expect:['batterie completement vide','borne','teste avec VOM'] },
{ id:64, make:'Suzuki', model:'Swift V', year:2018, fuel:'essence mild hybrid', km:41000, sys:'ISG',
  msg:'Suzuki Swift 1.2 DualJet MHEV 2018 41000km. ISG (start/stop etendu) desactive par lui-meme. Batterie auxiliaire 12V.', expect:['batterie lithium ISG','temperature','remplacement'] },
{ id:65, make:'Land Rover', model:'Range Rover Evoque II', year:2019, fuel:'hybride doux', km:56000, sys:'MHEV 48V',
  msg:'Range Rover Evoque 2.0 MHEV 2019 56000km. Freinage regeneratif saccade en ville. Batterie 48V en defaut.', expect:['batterie 48V','recuperation energie','mode degrade'] },

// ── GROUPE 5 : Emission / depollution (15) ─────────────────────────────────
{ id:66, make:'Volkswagen', model:'Touareg III', year:2019, fuel:'diesel', km:78000, sys:'SCR DEF',
  msg:'VW Touareg 3.0 TDI 2019 78000km. P20EE reactif NOx systeme SCR insuffisant. Niveau AdBlue OK.', expect:['capteur NOx','injecteur AdBlue','SCR'] },
{ id:67, make:'BMW', model:'X5 G05', year:2020, fuel:'diesel', km:54000, sys:'DOC + FAP + SCR',
  msg:'BMW X5 30d 2020 54000km. Sequence complete DPF+SCR en defaut, regeneration impossible. Utilisation courte distance.', expect:['trajets courts','conduite autoroute','regeneration forcee'] },
{ id:68, make:'Mercedes', model:'GLC W253', year:2018, fuel:'diesel', km:87000, sys:'BlueTEC',
  msg:'Mercedes GLC 220d 2018 87000km. P20BA pression injection AdBlue insuffisante. Pompe circuit AdBlue?', expect:['pompe AdBlue','filtre','circuit chauffant'] },
{ id:69, make:'Renault', model:'Trafic III', year:2017, fuel:'diesel', km:178000, sys:'EGR + FAP utilitaire',
  msg:'Renault Trafic 1.6 dCi 2017 178000km. EGR + FAP tous deux en defaut. Puissance limitee 60%. Circuit utilisateur pro.', expect:['utilisation pro','cartographie','nettoyage simultanee'] },
{ id:70, make:'Audi', model:'A4 B9', year:2016, fuel:'diesel', km:112000, sys:'EGR liquide',
  msg:'Audi A4 2.0 TDI 2016 112000km. P0401 EGR + surchauffe eau. Vanne EGR haute pression avec radiateur?', expect:['EGR liquide','radiateur EGR','byepass'] },
{ id:71, make:'Peugeot', model:'Expert III', year:2018, fuel:'diesel', km:134000, sys:'FAP utilitaire',
  msg:'Peugeot Expert 2.0 BlueHDi 2018 134000km. FAP bouche, compteur suie 80%, regeneration impossible courte distance.', expect:['FAP regeneration forcee','additif Eolys','temperature'] },
{ id:72, make:'Toyota', model:'Land Cruiser 150', year:2017, fuel:'diesel', km:145000, sys:'DOC',
  msg:'Toyota Land Cruiser 2.8 D-4D 2017 145000km. P2463 masse de suies elevee. Conduite tout terrain, regime bas constant.', expect:['regeneration impossible','regime bas','conduite autoroute'] },
{ id:73, make:'Citroen', model:'Jumper III', year:2016, fuel:'diesel', km:198000, sys:'EGR utilitaire',
  msg:'Citroen Jumper 2.2 HDi 2016 198000km. Perte puissance progressive. EGR collée ouverte, circuit admission carbonne.', expect:['nettoyage admission','EGR bloquee','rendement perdu'] },
{ id:74, make:'Ford', model:'Transit Connect', year:2019, fuel:'diesel', km:87000, sys:'SCR',
  msg:'Ford Transit Connect 1.5 EcoBlue 2019 87000km. Alarme AdBlue 2000km. Niveau bas mais reservoir plein?', expect:['capteur niveau','qualite AdBlue','circuit AdBlue'] },
{ id:75, make:'Volvo', model:'V60 II', year:2018, fuel:'diesel', km:94000, sys:'FAP + DPF',
  msg:'Volvo V60 D4 2018 94000km. DPF saturation 95% suie. Regeneration lancee mais arretee par temperature ambiante?', expect:['temperature regeneration','conditions','minimum vitesse'] },

// Emissions fin
{ id:76, make:'Skoda', model:'Superb III', year:2019, fuel:'diesel', km:76000, sys:'EGR haute pression',
  msg:'Skoda Superb 2.0 TDI 2019 76000km. P0401 + leger sifflement admission. Vanne EGR HP collée fermee?', expect:['EGR HP','nettoyage','vanne a papillon'] },
{ id:77, make:'Seat', model:'Leon III', year:2016, fuel:'diesel', km:103000, sys:'EGR basse pression',
  msg:'Seat Leon 1.6 TDI 2016 103000km. P0401 avec cliquetis discret a froid. Dépot carbonne EGR BP probable.', expect:['EGR BP','nettoyage','carbonne admission'] },
{ id:78, make:'Nissan', model:'NV200', year:2015, fuel:'diesel', km:167000, sys:'EGR + refroidisseur',
  msg:'Nissan NV200 1.5 dCi 2015 167000km. EGR + refroidisseur EGR en defaut. Consommation eau imperceptible.', expect:['refroidisseur EGR','fissure','circuit eau'] },
{ id:79, make:'Dacia', model:'Sandero II', year:2017, fuel:'diesel', km:78000, sys:'FAP sans additif',
  msg:'Dacia Sandero 1.5 dCi 2017 78000km. FAP sature 85%. Modele sans additif Eolys. Regeneration longue?', expect:['regeneration passive','conditions','autoroute'] },
{ id:80, make:'Mitsubishi', model:'Outlander PHEV', year:2019, fuel:'hybride rechargeable', km:54000, sys:'PHEV + FAP',
  msg:'Mitsubishi Outlander PHEV 2019 54000km. FAP sature en mode electrique pur constant. Moteur thermique jamais chaud.', expect:['moteur froid','FAP PHEV','regeneration auto'] },

// ── GROUPE 6 : Systemes freinage / ABS / ESP (10) ──────────────────────────
{ id:81, make:'Renault', model:'Espace V', year:2016, fuel:'diesel', km:89000, sys:'ABS+ESP',
  msg:'C1201 systeme ABS pression frein insuffisante. Renault Espace 1.6 dCi 2016 89000km. ESP desactive automatiquement.', expect:['ABS','capteur pression','accumulateur'] },
{ id:82, make:'BMW', model:'Série 3 G20', year:2020, fuel:'essence', km:38000, sys:'Frein de parc electricite',
  msg:'BMW 320i G20 2020 38000km. Frein de stationnement electrique ne se deserre pas au demarrage. Voyant rouge.', expect:['EMF','moteur frein','reset'] },
{ id:83, make:'Mercedes', model:'Viano W639', year:2013, fuel:'diesel', km:198000, sys:'ESP',
  msg:'Mercedes Viano 3.0 CDI 2013 198000km. ESP desactive en permanence, voyant allume. Plusieurs capteurs en defaut.', expect:['capteurs roue','ESP','diagnostic'] },
{ id:84, make:'Volkswagen', model:'Sharan II', year:2015, fuel:'diesel', km:134000, sys:'ABS',
  msg:'VW Sharan 2.0 TDI 2015 134000km. ABS se declenche a basse vitesse (<30km/h) sur route seche.', expect:['capteur vitesse roue','anneau ABS','roulement'] },
{ id:85, make:'Audi', model:'Q7 4M', year:2016, fuel:'diesel', km:89000, sys:'Freinage pneumatique',
  msg:'Audi Q7 3.0 TDI 2016 89000km. Suspensions pneumatiques baissent en stationnement. Compresseur qui travaille a froid.', expect:['fuite suspension pneumatique','valve','compresseur'] },
{ id:86, make:'Peugeot', model:'2008 II', year:2020, fuel:'electrique', km:27000, sys:'Frein regen',
  msg:'Peugeot e-2008 2020 27000km. Freinage regeneratif qui a-coupe a vitesse moderee. Batterie froide.', expect:['temperature batterie','limitation regen','normal hiver'] },
{ id:87, make:'Ford', model:'Mondeo V', year:2016, fuel:'diesel', km:112000, sys:'Correcteur frein',
  msg:'Ford Mondeo 2.0 TDCi 2016 112000km. Vehicule tourne a droite au freinage. Difference hydraulique?', expect:['etrier grippé','frein','comparaison'] },
{ id:88, make:'Toyota', model:'Hilux VIII', year:2019, fuel:'diesel', km:87000, sys:'Freinage 4x4',
  msg:'Toyota Hilux 2.8 D-4D 4x4 2019 87000km. Blocage differentiel qui engage mal, voyant clignote.', expect:['diff lock','actionneur','Toyota specific'] },
{ id:89, make:'Hyundai', model:'Santa Fe IV', year:2019, fuel:'diesel', km:56000, sys:'AEB',
  msg:'Hyundai Santa Fe 2.2 CRDi 2019 56000km. Freinage d urgence autonome (AEB) declenche intempestivement en ville.', expect:['radar AEB','calibration','pare-brise propre'] },
{ id:90, make:'Volvo', model:'XC90 II', year:2016, fuel:'diesel', km:98000, sys:'City Safety',
  msg:'Volvo XC90 D5 2016 98000km. City Safety desactive, message pare-brise non propre alors que c est bon.', expect:['capteur radar','temperature','reinitialisation'] },

// ── GROUPE 7 : Refroidissement + climatisation (10] ───────────────────────
{ id:91, make:'Renault', model:'Megane III RS', year:2013, fuel:'essence', km:134000, sys:'Refroidissement sport',
  msg:'Renault Megane RS 2.0 265ch 2013 134000km. Temperature moteur qui grimpe lors d utilisation circuit. Pompe eau ok.', expect:['thermostat','radiateur sport','utilisation intensive'] },
{ id:92, make:'BMW', model:'M3 F80', year:2015, fuel:'essence', km:56000, sys:'Refroidissement charge',
  msg:'BMW M3 3.0 biturbo F80 2015 56000km. Temperature admission grimpe sur piste, puissance coupee. Echangeur air-eau.', expect:['intercooler eau','echangeur','refroidissement eau charge'] },
{ id:93, make:'Ford', model:'Focus RS MK3', year:2016, fuel:'essence', km:43000, sys:'Diff actif GKN',
  msg:'Ford Focus RS MK3 2016 43000km. Surchauffe embrayage differentiels arriere lors de conduite sportive. Message defaut.', expect:['diff active','surchauffe','conduite normale recommandee'] },
{ id:94, make:'Volkswagen', model:'T6 Multivan', year:2018, fuel:'diesel', km:134000, sys:'Circuit chauffage',
  msg:'VW T6 2.0 TDI 2018 134000km. Chauffage insufflant froid uniquement a droite (cote passager). Gauche chaud.', expect:['vanne chauffage droite','capteur temperature dual zone','probleme distribution'] },
{ id:95, make:'Citroën', model:'SpaceTourer', year:2017, fuel:'diesel', km:87000, sys:'Climatisation diesel',
  msg:'Citroen SpaceTourer 2.0 BlueHDi 2017 87000km. Clim insuffisante sur 3e rangee. Avant tres froid, arriere tiede.', expect:['compresseur debit','circuit arriere','expansion valve'] },
{ id:96, make:'Mercedes', model:'Classe E W213', year:2016, fuel:'essence', km:76000, sys:'AIRMATIC',
  msg:'Mercedes Classe E E220 2016 76000km. Message AIRMATIC defaut, suspensions en mode urgence. Compresseur OK.', expect:['valve AIRMATIC','capteur hauteur','soufflet'] },
{ id:97, make:'Audi', model:'A8 D5', year:2018, fuel:'diesel', km:54000, sys:'48V PHEV suspension',
  msg:'Audi A8 3.0 TDI MHEV 2018 54000km. Suspension active eAWS ne compense plus. Batterie 48V 80% sante.', expect:['suspension active','48V','degradation naturelle'] },
{ id:98, make:'Porsche', model:'Cayenne III', year:2019, fuel:'essence', km:43000, sys:'Refroidissement V6',
  msg:'Porsche Cayenne 3.0 V6 Turbo 2019 43000km. Petite fuite eau sous voiture uniquement apres arret moteur chaud.', expect:['joint', 'durite','normal expansion','retour thermostat'] },
{ id:99, make:'Land Rover', model:'Defender L663', year:2021, fuel:'diesel', km:38000, sys:'Refroidissement mild hybrid',
  msg:'Land Rover Defender 2.0 D200 MHEV 2021 38000km. Temperature moteur stable mais ventilateurs tournent fort au ralenti.', expect:['normal diesel moderne','ventilateurs','regime'] },
{ id:100,make:'Tesla', model:'Model 3 LR', year:2021, fuel:'electrique', km:67000, sys:'Thermique batterie',
  msg:'Tesla Model 3 Long Range 2021 67000km. Preconditionnement batterie ne fonctionne pas avant recharge rapide. Temperature -3°C.', expect:['preconditionnement','Tesla app','batterie froide'] },
];
